### ISSUE TITLE
Setting text size for picker items.

### ISSUE THREAD

**Issue by Westycoot** [RameshBhupathi/PickerView#4]
I cannot find a way to change the text size for picker items. Could you point me in the right direction?

Great contribution otherwise!

**Comment by RameshBhupathi** [comment]
For font size we have attribute textSize try this...
**<attr name="textSize" format="dimension"/>**

**Comment by maheswaranecemohan** [comment]
Hai,
i can't find a way to change the font style for picker item. 

Grt Work !!!

**Comment by zarvedan** [comment]
You should create bools.xml :

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <bool name="pickerview_customTextSize">true</bool>
</resources>`

and in your dimens.xml, add :

` <dimen name="pickerview_textsize">14sp</dimen>`

**Comment by dhruv270** [comment]
@RameshBhupathi @zarvedan Can anyone pls guide me in details that how can I change the font size?

**Comment by RameshBhupathi** [comment]
@dhruv270 try this For font size we have attribute textSize try this...
<attr name="textSize" format="dimension"/>

**Comment by dhruv270** [comment]
Thanks a lot!
