### ISSUE TITLE
How to use double picker 

### ISSUE THREAD

**Issue by faizan321** [RameshBhupathi/PickerView#8]
How to use double picker?

**Comment by AnirudhLoya** [comment]
`       twoPicker = new MyOptionsPickerView(MainActivity.this);
        final ArrayList<String> twoItemsOptions1 = new ArrayList<String>();
        twoItemsOptions1.add("AA");
        twoItemsOptions1.add("BB");
        twoItemsOptions1.add("CC");
        twoItemsOptions1.add("DD");
        twoItemsOptions1.add("EE");
        final ArrayList<String> twoItemsOptions2 = new ArrayList<String>();
        twoItemsOptions2.add("00");
        twoItemsOptions2.add("11");
        twoItemsOptions2.add("22");
        twoItemsOptions2.add("33");
        twoItemsOptions2.add("44");

        twoPicker.setPicker(twoItemsOptions1, twoItemsOptions2, false);
        twoPicker.setTitle("Picker");
        twoPicker.setCyclic(false, false, false);
        twoPicker.setSelectOptions(0, 0);
        twoPicker.setOnoptionsSelectListener(new MyOptionsPickerView.OnOptionsSelectListener() {
            @Override
            public void onOptionsSelect(int options1, int option2, int options3) {
                // twoTVOptions.setText("Two Options " + twoItemsOptions1.get(options1) + " " + twoItemsOptions2.get(option2));
                vMasker.setVisibility(View.GONE);
                Toast.makeText(MainActivity.this, "" + twoItemsOptions1.get(options1) + " " + twoItemsOptions2.get(option2), Toast.LENGTH_SHORT).show();
            }
        });
`
Check Sample App , u can find easily

**Comment by RameshBhupathi** [comment]
`   //Two Options PickerView
        twoPicker = new MyOptionsPickerView(MainActivity.this);
        final ArrayList<String> twoItemsOptions1 = new ArrayList<String>();
        twoItemsOptions1.add("AA");
        twoItemsOptions1.add("BB");
        twoItemsOptions1.add("CC");
        twoItemsOptions1.add("DD");
        twoItemsOptions1.add("EE");
        final ArrayList<String> twoItemsOptions2 = new ArrayList<String>();
        twoItemsOptions2.add("00");
        twoItemsOptions2.add("11");
        twoItemsOptions2.add("22");
        twoItemsOptions2.add("33");
        twoItemsOptions2.add("44");

        twoPicker.setPicker(twoItemsOptions1, twoItemsOptions2, false);
        twoPicker.setTitle("Picker");
        twoPicker.setCyclic(false, false, false);
        twoPicker.setSelectOptions(0, 0);
        twoPicker.setOnoptionsSelectListener(new MyOptionsPickerView.OnOptionsSelectListener() {
            @Override
            public void onOptionsSelect(int options1, int option2, int options3) {
                // twoTVOptions.setText("Two Options " + twoItemsOptions1.get(options1) + " " + twoItemsOptions2.get(option2));
                vMasker.setVisibility(View.GONE);
                Toast.makeText(MainActivity.this, "" + twoItemsOptions1.get(options1) + " " + twoItemsOptions2.get(option2), Toast.LENGTH_SHORT).show();
            }
        });`
Check Sample app u can find easily
