### ISSUE TITLE
Not shure about licence

### ISSUE THREAD

**Issue by lichterschalter** [RameshBhupathi/PickerView#9]
Hi Ramesh Bhupathi, 
I would like to use your great library as a student for a university project in computer science. I´m not complete shure about your licencing: the code is licenced under apache licence version 2.0, but above you put a copyright statement. Would it be okay for you, if I use your library for this (non-commercial) university project? I would cite it of course!
All the best
lichterschalter

**Comment by RameshBhupathi** [comment]
Hi lichterschalter,
Your are Wellcome, U can use it for Commercial Purpose also.

**Comment by lichterschalter** [comment]
Thanks! :)
